
// Autogenerated by geninfo, do not edit

package gcewing.architecture;

public class Info {

    static final String modName = "ArchitectureCraft";
    static final String modID = "ArchitectureCraft";
    static final String versionNumber = "1.3.5";
    static final String versionBounds = "[1.3,1.4)";
    static final String acceptedMinecraftVersions = "1.7.10";

}

