
// Autogenerated by geninfo, do not edit

package gcewing.architecture;

public class Info {

    static final String modName = "ArchitectureCraft";
    static final String modID = "ArchitectureCraft";
    static final String versionNumber = "GRADLETOKEN_VERSION";
    static final String acceptedMinecraftVersions = "1.7.10";

}
